import type { Metadata } from 'next'
import './globals.css'
import { SidebarProvider } from '@/components/ui/sidebar'
import AppSidebar from '@/components/AppSideBar/AppSideBar'
import Header from '@/components/Header/Header'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <SidebarProvider>
                    <AppSidebar />
                    <main className="w-full ">
                        <Header />
                        {children}
                    </main>
                </SidebarProvider>
            </body>
        </html>
    )
}
